batch_size: 1
iters: 10000

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    in_channels: 2
  num_classes: 2
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/cityscapes/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k/model.pdparams

train_dataset:
  type: Dataset
  dataset_root: data/train
  train_path: data/train/train.txt
  num_classes: 2
  img_channels: 2
  mode: train
  transforms:
    - type: Resize
      target_size: [1024, 1024]
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/train
  val_path: data/train/val.txt
  num_classes: 2
  img_channels: 2
  mode: val
  transforms:
    - type: Resize
      target_size: [1024, 1024]
    - type: Normalize

optimizer:
  type: Adam
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9

loss:
  types:
    - type: BCELoss
      pos_weight: dynamic
  coef: [1]
